### ISSUE TITLE
Does this method perform well on high dynamic scene?

### ISSUE THREAD

**Issue by kexul** [PKU-VCL-3DV/SLAM3R#4]
Hi, thanks for your great work! I'd like to know how it perform on high dynamic scene? Have you tried compare it with [Monst3R](https://github.com/Junyi42/monst3r)?

**Comment by siyandong** [comment]
Thank you for your interest! SLAM3R is currently trained only on static scenes and cannot handle dynamic scenes.

**Comment by kexul** [comment]
> Thank you for your interest! SLAM3R is currently trained only on static scenes and cannot handle dynamic scenes.

Thanks!
